whitespace changes on user scripts (tab => 4 spaces)

diff --git a/user_files/local/bin/hibernate b/user_files/local/bin/hibernate
--- a/user_files/local/bin/hibernate
+++ b/user_files/local/bin/hibernate
@@ -10,15 +10,15 @@ SYSTEMCTL="$(which systemctl 2>/dev/null)"
 
 if [ -z "$SYSTEMCTL" ]
 then
-	exit 127
+    exit 127
 fi
 
 CMD="$SYSTEMCTL hibernate"
 
 if ! $CMD
 then
-	printf "\nunable to run \"%s\"\n\n" "$CMD"
-	exit 127
+    printf "\nunable to run \"%s\"\n\n" "$CMD"
+    exit 127
 fi
 
 $LOCK
